---
 - hosts: localhost
   become_method: sudo
   remote_user: pscheid

   tasks:    
    - name: update all packages
      become: true
      dnf:
        name: "*"
        state: latest

    - name: install shell and tools
      become: true
      dnf:
        name:
          - zsh
          - tilix
          - tilix-nautilus
          - moreutils
          - pixz

    - name: clone oh-my-zsh
      git:
        repo: git@github.com:robbyrussell/oh-my-zsh.git
        dest: /home/pscheid/.oh-my-zsh
        accept_hostkey: yes
        key_file: /home/pscheid/.ssh/id_rsa
    
    - name: clone my private dotfiles
      git:
        repo: git@github.com:pscheid92/dotfiles.git
        dest: /home/pscheid/.dotfiles
        accept_hostkey: yes
        key_file: /home/pscheid/.ssh/id_rsa

    - name: link dotfile configuration files
      script: /home/pscheid/.dotfiles/install

    - name: change shell to zsh
      shell: chsh -s /bin/zsh pscheid

    - name: install dependencies for asdf-vm
      become: true
      dnf:
        name:
          - automake
          - autoconf
          - readline-devel
          - ncurses-devel
          - openssl-devel
          - libyaml-devel
          - libxslt-devel
          - libffi-devel
          - libtool
          - unixODBC-devel
          - unzip
          - curl

    - name: copy asdf repository
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: /home/pscheid/.asdf
        version: v0.7.4

    - name: configure plugins and languages asdf
      script: configure_asdf.sh
    
    - name: install jetbrains toolbox
      script: install_jetbrains_toolbox.sh

    - name: install calibre
      become: true
      dnf:
        name: calibre
    
    - name: install graphic software
      become: true
      dnf:
        name:
          - gimp
          - inkscape

    - name: install printing and scanning
      become: true
      dnf:
        name:
          - hplip
          - hplip-gui
          - xsane

    - name: install gnome tweak tool
      become: true
      dnf:
        name: gnome-tweaks

    - name: install google-chrome repository
      become: true
      script: install_google_chrome.sh

    - name: install dbeaver database client
      become: true
      dnf:
        name: 'https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm'

    - name: install visual Studio code
      become: true
      script: install_visual_studio_code.sh

    - name: install docker and docker-compose
      become: true
      script: install_docker.sh

    - name: install meld as mergeconflict tool
      become: true
      dnf:
        name: meld

    - name: install insync
      become: true
      script: install_insync.sh
