---
 - hosts: localhost
   become_method: sudo
   remote_user: pscheid

   tasks:
    - name: update all packages
      become: true
      dnf:
        name: "*"
        state: latest

    - name: install shell and tools
      become: true
      dnf:
        name:
          - zsh
          - tilix
          - tilix-nautilus
          - moreutils
          - pixz

    - name: clone oh-my-zsh
      git:
        repo: git@github.com:robbyrussell/oh-my-zsh.git
        dest: /home/pscheid/.oh-my-zsh
        accept_hostkey: yes
        key_file: /home/pscheid/.ssh/id_rsa

    - name: clone my private dotfiles
      git:
        repo: git@github.com:pscheid92/dotfiles.git
        dest: /home/pscheid/.dotfiles
        accept_hostkey: yes
        key_file: /home/pscheid/.ssh/id_rsa

    - name: link dotfile configuration files
      script: /home/pscheid/.dotfiles/install

    - name: change shell to zsh
      shell: chsh -s /bin/zsh pscheid

    - name: install dependencies for asdf-vm
      become: true
      dnf:
        name:
          - automake
          - autoconf
          - readline-devel
          - ncurses-devel
          - openssl-devel
          - libyaml-devel
          - libxslt-devel
          - libffi-devel
          - libtool
          - unixODBC-devel
          - unzip
          - curl

    - name: copy asdf repository
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: /home/pscheid/.asdf

    - name: configure plugins and languages asdf
      script: install_scripts/install_asdf.sh

    - name: install rlwrap as dependency for clojure
      become: true
      dnf:
        name:
          - rlwrap

    - name: install jetbrains toolbox
      script: install_scripts/install_jetbrains_toolbox.sh

    - name: install graphic and office software
      become: true
      dnf:
        name:
          - calibre
          - gimp
          - inkscape
          - hplip
          - hplip-gui
          - pdfmod
          - xsane
          - paperwork
          - tesseract-langpack-deu

    - name: install gnome tweak tool
      become: true
      dnf:
        name: gnome-tweaks

    - name: install google-chrome repository
      become: true
      script: install_scripts/install_google_chrome.sh

    - name: install dbeaver database client
      become: true
      dnf:
        name: 'https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm'

    - name: install meld as mergeconflict tool
      become: true
      dnf:
        name: meld

    - name: install insync
      become: true
      script: install_scripts/install_insync.sh

    - name: install rambox
      become: true
      dnf:
        name: 'https://github.com/ramboxapp/community-edition/releases/download/0.7.3/Rambox-0.7.3-linux-x86_64.rpm'

    - name: install visual studio code
      become: true
      script: install_scripts/install_visual_studio_code.sh

    - name: install docker and docker-compose
      become: true
      script: install_scripts/install_docker.sh

    - name: install kubectl
      become: true
      script: install_scripts/install_kubectl.sh

    - name: install minikube
      become: true
      script: install_scripts/install_minikube.sh

    - name: install podman
      become: true
      dnf:
        name:
          - podman
          - podman-compose

    - name: install teamviewer
      become: true
      script: install_scripts/install_teamviewer.sh

    - name: install spotify
      flatpak:
        name: com.spotify.Client
        state: present

    - name: install vlc player
      flatpak:
        name: org.videolan.VLC
        state: present

    - name: install dropbox
      become: true
      script: install_scripts/install_dropbox.sh

    - name: install microsoft r open
      become: true
      script: install_scripts/install_mro.sh

    - name: install rstudio
      become: true
      dnf:
        name: 'https://download1.rstudio.org/desktop/fedora28/x86_64/rstudio-1.2.5033-x86_64.rpm'

    - name: install leela gui
      become: true
      dnf:
        name: 'https://sjeng.org/dl/leela-0.11.0-1.x86_64.rpm'

    - name: install k6
      become: true
      script: install_scripts/install_k6.sh

    - name: install websocat
      become: true
      script: install_scripts/install_websocat.sh

    - name: install localstack
      become: true
      pip:
        name: localstack[full]
        executable: pip3

    - name: install awslocal cli
      become: true
      pip:
        name: awscli-local
        executable: pip3

    - name: install aws cli
      become: true
      script: install_scripts/install_awscli.sh

    - name: install terraform
      become: true
      script: install_scripts/install_terraform.sh

    - name: install angular cli
      become: false
      script: install_scripts/install_angular_cli.sh
